name: code lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-lint:
    name: code lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: lint php files
        run: bash scripts/lint-php.sh

      - name: lint javascript files
        run: bash scripts/lint-javascript.sh

      - name: lint css files
        run: bash scripts/lint-css.sh
